id = "comment"
name = "Comment Highlighting"
version = "0.1.0"
schema_version = 1
authors = ["anphir"]
description = "Highlighting of alerts (NOTE:, TODO:, ...) and URIs in comments for languages supporting this extension."
repository = "https://github.com/anphir/zed-comment.git"

[grammars.comment]
repository = "https://github.com/stsewd/tree-sitter-comment.git"
# This is version 0.3.0.
rev = "689be73775bd2dd57b938b8e12bf50fec35a6ca3"
